// react/nossa-galeria-modal/src/App.tsx
import React, { useEffect, useState } from 'react';
import { Modal } from './Modal';
import './App.css';
import axios from 'axios';

function App() {
  const url = 'http://localhost:4000/catGallery';
  const [showGallery, setShowGallery] = useState<any[]>([]);
  const [openModal, setOpenModal] = useState(false);
  const open = () => setOpenModal(true);

  const fetchData = async () => {
    const { data } = await axios.get(url);
    setShowGallery(data);
  }

  useEffect(() => {
    fetchData()
  }, [])

  return (
    <div className="App">
      <section className="grid-section">
        {showGallery.map(cat => (
          <div className="grid">
            <div className="grid-img">
              <img src={cat.imgLink} alt="Gatos" />
            </div>
            <div className="overlay">
              <h2>{cat.title}</h2>
              <button className="btn">Enter</button>
            </div>
          </div>
        ))}
      </section>
    </div>
  );
}

export default App;

// angular/angular-galeria-modal/src/app/app.component.ts
import { Component } from '@angular/core';
import { cats } from './cats';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Nossa galeria com modal';

  cats = cats;

  showModal: boolean = false;

  imageSrc: string = '';


  openModal(image: any): void {
    this.showModal = true;
    this.imageSrc = image.imgLink;
  }

  closeModal(): void {
    this.showModal = false;
  }
}

<body>
  <section class="grid-section">
    <div class="grid" *ngFor="let cat of cats">
      <div class="grid-img">
        <img src="{{cat.imgLink}}">
      </div>
      <div class="overlay">
        <h2>{{cat.title}}</h2>
        <button class="btn" (click)="openModal(cat)">Enter</button>
      </div>
    </div>
  </section>

  <section class="modal" *ngIf="showModal">
    <button class="modal-btn btn" (click)="closeModal()" >Close</button>
        <img src="{{imageSrc}}" alt="" class="modal__content">
  </section>
</body>
